version: "3.9"

services:
  secure-chat-client:
    build: .
    container_name: secure-chat-client
    ports:
      - "8501:8501"            # ブラウザから http://localhost:8501
    # Mac の Docker Desktop では同一ホスト上のポートを
    #  name: host.docker.internal  で参照できる
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # client.py 内で server を 127.0.0.1 → host.docker.internal に
      # 変更しておくと、コンテナからホスト上のサーバへ届きます
      CHAT_SERVER_HOST: host.docker.internal
    # 必要に応じてログを見たい場合
    stdin_open: true
    tty: true
