name: Docker Build & Compose CI

on:
  push:
    paths:
      - 'client/**'
      - 'server/**'
      - 'docker-compose.yml'
      - '.github/workflows/ci.yml'
  pull_request:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: 📦 Checkout repository
      uses: actions/checkout@v3

    - name: 🐳 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔧 Build client and server containers
      run: docker-compose build

    - name: 🚀 Start containers
      run: |
        docker-compose up -d
        sleep 10
        docker ps

    - name: 🧹 Clean up containers
      if: always()
      run: docker-compose down
