name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存ライブラリのインストール
        run: |
          python -m pip install --upgrade pip
          pip install pytest pycryptodome streamlit streamlit-autorefresh

      - name: テスト実行
        run: |
          pytest -q
